language: android
# Enable container-based infrastructure
sudo: false
android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
branches:
  only:
    - master
before_install:
    - echo "stub keystore" > cmp.keystore
    - echo "stub storage pwd" > cmpstorage.pwd
    - echo "stub key pwd" > cmpkey.pwd
    - chmod +x gradlew
script:
    - ./gradlew clean assembleGooglePlayTravis
